version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - nota-fiscal-network

networks:
  nota-fiscal-network:
    driver: bridge