version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nota-fiscal-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 10s
      retries: 5

  estoque-service:
    image: estoque-service
    build:
      context: .
      dockerfile: EstoqueService/Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - ./EstoqueService/Data:/app/Data
    networks:
      - nota-fiscal-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  faturamento-service:
    image: faturamento-service
    build:
      context: .
      dockerfile: FaturamentoService/Dockerfile
    ports:
      - "5002:8080"
    volumes:
      - ./FaturamentoService/Data:/app/Data
    environment:
      - EstoqueService__BaseUrl=http://estoque-service:8080
    networks:
      - nota-fiscal-network
    depends_on:
      - rabbitmq
      - estoque-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  nota-fiscal-network:
    driver: bridge